language: java
sudo: required

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk11

services:
  - docker

before_install:
  - mvn package
  - docker build -t galkilani/aws-app .

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "aws-app"
  env: "awsapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-814158934529"
  bucket_path: "aws-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
